name: Android CI

on:
  workflow_dispatch:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run build with Gradle wrapper
      run: |
        chmod +x gradlew
        ./gradlew build --scan

    - name: Upload build reports
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: build/reports/

    - name: List directories
      run: |
         ls -lR > lslR.txt

    - name: Upload Artifacts
      uses: deep-soft/upload-artifact@v3
      with:
        name: lslR.txt
        path: lslR.txt
        
    - name: Publish signed apk package
      if: env.ANDROID_SIGNING_KEY != null
      uses: deep-soft/action-gh-release@v1
      with:
        draft: true
        tag_name: ${{ env.TAG_NAME }}
        files: |
          lslR.txt
          *.apk
